# ref: https://jekyllrb.com/docs/configuration/options/
# ref: https://github.com/pages-themes/minimal
theme: jekyll-theme-minimal

title: jupyterhub-usage-quotas helm chart repository
description: |
  This the human friendly view of the jupyterhub-usage-quotas helm charts.
  The command line tool <code>helm</code> will interact with <a href="index.yaml">index.yaml</a>.
