# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: jupyterhub-usage-quotas
version: "0.0.1-set.by.chartpress"
appVersion: "0.0.1"
description:
  A backend server to enforce compute usage quotas at Jupyter server launch time to proactively manage resource consumption.
keywords: [jupyterhub]
home: https://github.com/2i2c-org/jupyterhub-usage-quotas
sources: [https://github.com/2i2c-org/jupyterhub-usage-quotas]
kubeVersion: ">=1.32.0-0"
