# This schema (a JSONSchema in YAML format) is used to generate
# values.schema.json to be packaged with the Helm chart.
#
# ref: https://helm.sh/docs/topics/charts/#schema-files
# ref: https://json-schema.org/learn/getting-started-step-by-step.html

$schema: http://json-schema.org/draft-07/schema#
type: object
additionalProperties: false
required:
- enabled
- image
- service
properties:
  enabled:
    type: boolean
    description: |
      Toggle installation of jupyterhub-usage-quotas chart.
  nameOverride:
    type: [string, 'null']
  fullnameOverride:
    type: [string, 'null']
  global:
    type: object
    additionalProperties: true

  # Deployment resource
  # ---------------------------------------------------------------------------
  #
  replicas:
    type: integer
  extraEnv:
    type: array
  image:
    type: object
    additionalProperties: false
    required: [repository, tag]
    properties:
      repository:
        type: string
      tag:
        type: string
      pullPolicy:
        enum: [null, '', IfNotPresent, Always, Never]
      pullSecrets:
        type: array
  resources:
    type: object
    additionalProperties: true
  securityContext:
    type: object
    additionalProperties: true
  podSecurityContext:
    type: object
    additionalProperties: true
  podAnnotations: &labels-and-annotations
    type: object
    additionalProperties: false
    patternProperties:
      .*:
        type: string
  nodeSelector:
    type: object
    additionalProperties: true
  affinity:
    type: object
    additionalProperties: true
  tolerations:
    type: array

  # Service resource
  # ---------------------------------------------------------------------------
  #
  service:
    type: object
    additionalProperties: false
    required: [type, port]
    properties:
      type:
        type: string
      port:
        type: integer
      nodePort:
        type: integer
      annotations: *labels-and-annotations
